### ISSUE TITLE
Adding Essential Repositories/ Basic Structure to the Organisation

### ISSUE THREAD

**Issue by Yash-Handa** [gdgcloudnd/gdgc-1yr-team1#1]
Hi @pranaynanda,
I think there is space for some more repositories on this Organization which can add basic structure to it. I recommend adding these repositories to the Organization:-

### talks (Collection of all the talks in one place)
- **Purpose**: Anyone who wants to take a session can simply **open an Issue** to this repository
- list of all the talks with links for ppt/videos/code
- People can open issues for submitting a talk in future
- Guidelines/Tips for submitting a talk/taking a session

### gcdc-nd.github.io
- **Purpose**: gdgc official web site
- **Notes**: Work could be done in future

### resources (contain the official resources)
- Images/banners (SVG and png)
- Text templates (tweet template, message/meetup template, official venue email)

### volunteers
- code of conduct for volunteers
- List of active volunteers and other positions like organizers, etc
- List of working groups/teams + members in them

### CoreMemberMeeting
- List of meetings of core members
- To Do/Future planes(topics)
- Suggested meetup topics

### About
- Vision and Mission
- Based on (location)
- Slack/GoogleGroup/Email
- Twitter handle/facebook page, etc

### Repos for specific labs/workshops/events/talks

**Metadata: Adition of Logo, email, location, website to the Organization page**

**Inspiration**: [Node.js](https://github.com/nodejs), [PyDelhi](https://github.com/pydelhi), [GDG New Delhi](https://github.com/gdgnewdelhi), [GDG Cochin](https://github.com/GDGCochin)

**Comment by Yash-Handa** [comment]
I would love to contribute to **GCDC New Delhi** by Adding these repositories to the Organization. Please let me what you think about it so that I can start working on it :)

**Comment by pranaynanda** [comment]
Hi Yash, I like the idea. To some extent, the part about listing all the talks of an individual is being handled by our current tool, Commudle. Same goes for the website. Everything else is great. We can discuss more on other channels.
